export interface Exercise {
  id: string;
  name: string;
  category: ExerciseCategory;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  stabilizerMuscles: string[];
  equipment: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  technique: string[];
  tips: string[];
  commonMistakes: string[];
  videoUrl: string;
  alternatives: string[];
}

export type ExerciseCategory =
  | 'chest'
  | 'back'
  | 'shoulders'
  | 'biceps'
  | 'triceps'
  | 'legs'
  | 'glutes'
  | 'core'
  | 'cardio'
  | 'full_body';

export const CATEGORY_LABELS: Record<ExerciseCategory, string> = {
  chest: 'Chest',
  back: 'Back',
  shoulders: 'Shoulders',
  biceps: 'Biceps',
  triceps: 'Triceps',
  legs: 'Legs',
  glutes: 'Glutes',
  core: 'Core',
  cardio: 'Cardio',
  full_body: 'Full Body',
};

export const EXERCISES: Exercise[] = [
  // ─── CHEST ───────────────────────────────────────────────────────────────
  {
    id: 'barbell_bench_press',
    name: 'Barbell Bench Press',
    category: 'chest',
    primaryMuscles: ['Pectoralis Major'],
    secondaryMuscles: ['Anterior Deltoid', 'Triceps Brachii'],
    stabilizerMuscles: ['Rotator Cuff', 'Serratus Anterior'],
    equipment: 'Barbell, Bench',
    difficulty: 'intermediate',
    technique: [
      'Lie flat on the bench with eyes under the bar; plant feet firmly on the floor.',
      'Grip the bar just outside shoulder width with a full thumb-around grip.',
      'Unrack the bar and lower it with control to the lower chest (nipple line), keeping elbows at ~75°.',
      'Touch the chest lightly without bouncing, then press explosively back to lockout.',
      'Maintain a slight natural arch in the lower back and keep shoulder blades retracted throughout.',
    ],
    tips: [
      'Think "bend the bar" to keep elbows tucked and protect shoulders.',
      'Drive your feet into the floor to create full-body tension.',
      'Lower the bar over 2–3 seconds; press as fast as technique allows.',
      'Keep your wrists stacked directly above your elbows at the bottom.',
    ],
    commonMistakes: [
      'Flaring the elbows to 90°, which stresses the shoulder joint.',
      'Bouncing the bar off the chest to use momentum instead of muscle.',
      'Lifting the hips off the bench, which reduces stability and power transfer.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=vcBig73ojpE',
    alternatives: ['incline_dumbbell_press', 'cable_fly', 'push_up', 'dips'],
  },
  {
    id: 'incline_dumbbell_press',
    name: 'Incline Dumbbell Press',
    category: 'chest',
    primaryMuscles: ['Pectoralis Major (Upper)'],
    secondaryMuscles: ['Anterior Deltoid', 'Triceps Brachii'],
    stabilizerMuscles: ['Rotator Cuff', 'Biceps Brachii (long head)'],
    equipment: 'Dumbbells, Incline Bench',
    difficulty: 'beginner',
    technique: [
      'Set the bench to 30–45°; sit back with a dumbbell on each knee.',
      'Kick the dumbbells up to shoulder height and lie back under control.',
      'Press the dumbbells up and slightly together, stopping just short of touching at the top.',
      'Lower with control until your elbows are just below bench level, feeling a stretch in the chest.',
      'Drive the dumbbells back up, squeezing the upper chest at the top.',
    ],
    tips: [
      'Use a 30–45° incline—steeper angles shift the load onto the front deltoid.',
      'Keep a neutral wrist and avoid letting the dumbbells drift toward the face.',
      'Pause briefly at the bottom stretch for greater muscle activation.',
    ],
    commonMistakes: [
      'Setting the incline too high (>45°), making it a shoulder press.',
      'Letting the dumbbells drift outward, losing tension on the pecs.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=8iPEnn-ltC8',
    alternatives: ['barbell_bench_press', 'cable_fly', 'push_up', 'dips'],
  },
  {
    id: 'cable_fly',
    name: 'Cable Fly',
    category: 'chest',
    primaryMuscles: ['Pectoralis Major'],
    secondaryMuscles: ['Anterior Deltoid'],
    stabilizerMuscles: ['Biceps Brachii', 'Core'],
    equipment: 'Cable Machine',
    difficulty: 'beginner',
    technique: [
      'Set both pulleys to chest height; stand in the center of the cable station.',
      'Grab a handle in each hand, step forward into a split stance, and lean slightly forward.',
      'With a slight bend in the elbows, bring the handles together in a wide arc in front of your chest.',
      'Squeeze the pecs hard at the peak contraction, holding for one count.',
      'Slowly return the handles along the same arc, feeling a full stretch in the chest.',
    ],
    tips: [
      'Think of hugging a large tree—elbows stay slightly bent throughout.',
      'Control the eccentric (opening) phase over 2–3 seconds for maximum stretch.',
      'Experiment with high, mid, and low pulley positions to hit different chest regions.',
    ],
    commonMistakes: [
      'Bending the elbows too much, turning it into a pressing movement.',
      'Using excessive weight that prevents a full range of motion.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=Iwe6AmxVf7o',
    alternatives: ['barbell_bench_press', 'incline_dumbbell_press', 'push_up', 'dips'],
  },
  {
    id: 'push_up',
    name: 'Push-Up',
    category: 'chest',
    primaryMuscles: ['Pectoralis Major'],
    secondaryMuscles: ['Anterior Deltoid', 'Triceps Brachii'],
    stabilizerMuscles: ['Core', 'Serratus Anterior'],
    equipment: 'Bodyweight',
    difficulty: 'beginner',
    technique: [
      'Place hands slightly wider than shoulder-width on the floor, fingers pointing forward.',
      'Extend your legs behind you, creating a straight line from head to heels.',
      'Brace your core and glutes to maintain a rigid plank position throughout.',
      'Lower your chest to within an inch of the floor, keeping elbows at ~45° from the torso.',
      'Press the floor away explosively to return to the starting position.',
    ],
    tips: [
      'Actively try to "spread the floor apart" with your hands to engage the chest more.',
      'Look at a spot 12 inches in front of your hands to keep a neutral neck.',
      'Add a pause at the bottom to eliminate momentum and increase difficulty.',
    ],
    commonMistakes: [
      'Letting the hips sag, creating a banana-back and reducing core engagement.',
      'Flaring elbows out to 90°, placing excessive stress on the shoulder joint.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
    alternatives: ['barbell_bench_press', 'incline_dumbbell_press', 'cable_fly', 'dips'],
  },
  {
    id: 'dips',
    name: 'Dips',
    category: 'chest',
    primaryMuscles: ['Pectoralis Major (Lower)'],
    secondaryMuscles: ['Triceps Brachii', 'Anterior Deltoid'],
    stabilizerMuscles: ['Rhomboids', 'Core'],
    equipment: 'Parallel Bars',
    difficulty: 'intermediate',
    technique: [
      'Grip the parallel bars and press up to the starting position with arms fully extended.',
      'Lean your torso slightly forward (15–30°) to shift emphasis to the chest.',
      'Lower yourself under control until your shoulders are at or just below elbow level.',
      'Keep elbows tracking back, not flaring outward.',
      'Press back up powerfully to full lockout, squeezing the chest at the top.',
    ],
    tips: [
      'The more you lean forward, the greater the chest stimulus; upright dips emphasize triceps.',
      'Cross your ankles behind you to reduce swinging.',
      'Add a weight belt or hold a dumbbell between your feet for progressive overload.',
    ],
    commonMistakes: [
      'Descending too deep beyond shoulder flexibility, risking a pec tear.',
      'Staying too upright, which turns it into a triceps exercise.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=2z8JmcrW-As',
    alternatives: ['barbell_bench_press', 'incline_dumbbell_press', 'cable_fly', 'push_up'],
  },

  // ─── BACK ─────────────────────────────────────────────────────────────────
  {
    id: 'deadlift',
    name: 'Deadlift',
    category: 'back',
    primaryMuscles: ['Erector Spinae', 'Latissimus Dorsi'],
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Trapezius'],
    stabilizerMuscles: ['Core', 'Forearms'],
    equipment: 'Barbell',
    difficulty: 'advanced',
    technique: [
      'Stand with feet hip-width apart, bar over mid-foot; grip just outside the legs.',
      'Hinge at the hips and bend the knees until shins touch the bar; keep chest up.',
      'Take a big breath into your belly, brace your core hard (360° tension), and pull the slack out of the bar.',
      'Drive the floor away, keeping the bar close to your body as your hips and shoulders rise together.',
      'Lock out by squeezing the glutes and standing tall; reverse the motion with control to set the bar down.',
    ],
    tips: [
      '"Protect your armpits"—engage the lats to keep the bar from drifting forward.',
      'Think "push the floor away" rather than "pull the bar up."',
      'Hip hinge to set up; the knees only bend enough to reach the bar.',
      'Keep your breath held and core braced until the rep is complete.',
    ],
    commonMistakes: [
      'Rounding the lower back under load, which can cause injury.',
      'Jerking the bar off the floor instead of pulling slack out first.',
      'Letting the bar drift away from the body, increasing the moment arm.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
    alternatives: ['pull_up', 'barbell_row', 'lat_pulldown', 'seated_cable_row', 'face_pull'],
  },
  {
    id: 'pull_up',
    name: 'Pull-Up',
    category: 'back',
    primaryMuscles: ['Latissimus Dorsi'],
    secondaryMuscles: ['Biceps Brachii', 'Rhomboids', 'Teres Major'],
    stabilizerMuscles: ['Core', 'Rotator Cuff'],
    equipment: 'Pull-Up Bar',
    difficulty: 'intermediate',
    technique: [
      'Hang from a bar with a pronated (overhand) grip, hands shoulder-width or slightly wider.',
      'Depress and retract your shoulder blades before initiating the pull.',
      'Drive your elbows down and back, pulling your chest toward the bar.',
      'Continue until your chin clears the bar, holding briefly at the top.',
      'Lower under full control until arms are straight before the next rep.',
    ],
    tips: [
      'Initiate the movement by "putting your shoulder blades in your back pockets."',
      'Avoid kipping—controlled reps build far more back strength.',
      'Use a false grip (no thumb wrap) to keep the focus on the back, not the biceps.',
    ],
    commonMistakes: [
      'Not achieving full extension at the bottom, reducing range of motion.',
      'Using momentum or kipping to complete the rep.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
    alternatives: ['deadlift', 'barbell_row', 'lat_pulldown', 'seated_cable_row', 'face_pull'],
  },
  {
    id: 'barbell_row',
    name: 'Barbell Row',
    category: 'back',
    primaryMuscles: ['Latissimus Dorsi', 'Rhomboids'],
    secondaryMuscles: ['Biceps Brachii', 'Rear Deltoid', 'Trapezius'],
    stabilizerMuscles: ['Erector Spinae', 'Core'],
    equipment: 'Barbell',
    difficulty: 'intermediate',
    technique: [
      'Stand with feet hip-width; hinge forward until your torso is ~45° from horizontal.',
      `Grip the bar just outside hip width with a pronated grip; let it hang at arm's length.`,
      'Pull the bar toward your lower ribcage, driving elbows back and squeezing the shoulder blades together.',
      'Pause briefly at the top with the bar touching the torso.',
      'Lower the bar under control back to full extension, maintaining the hip hinge.',
    ],
    tips: [
      'Keep your lower back neutral—not rounded—by engaging your core and glutes.',
      'Pull "through your elbows" rather than focusing on your hands.',
      'Aim to keep the bar path vertical to minimize lower back strain.',
    ],
    commonMistakes: [
      'Using excessive body English to heave the bar up.',
      'Standing too upright, which turns it into an upright row.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=FWJR5Ve8bnQ',
    alternatives: ['deadlift', 'pull_up', 'lat_pulldown', 'seated_cable_row', 'face_pull'],
  },
  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    category: 'back',
    primaryMuscles: ['Latissimus Dorsi'],
    secondaryMuscles: ['Biceps Brachii', 'Teres Major', 'Rhomboids'],
    stabilizerMuscles: ['Core', 'Rotator Cuff'],
    equipment: 'Cable Machine, Lat Bar',
    difficulty: 'beginner',
    technique: [
      'Sit at the machine and secure your thighs under the pads; grip the bar wider than shoulder-width.',
      'Lean back slightly (~15°) and depress your shoulder blades.',
      'Pull the bar to your upper chest, driving your elbows down and back.',
      'Squeeze the lats hard at the bottom and hold for one count.',
      'Slowly return the bar to full extension, feeling the lats stretch.',
    ],
    tips: [
      'Think about driving your elbows into your back pockets.',
      'Avoid pulling the bar behind the neck—this stresses the cervical spine.',
      'Use a moderate grip width; very wide grips reduce range of motion.',
    ],
    commonMistakes: [
      'Leaning back excessively, turning it into a rowing motion.',
      'Using arm strength instead of initiating with the lats.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
    alternatives: ['deadlift', 'pull_up', 'barbell_row', 'seated_cable_row', 'face_pull'],
  },
  {
    id: 'seated_cable_row',
    name: 'Seated Cable Row',
    category: 'back',
    primaryMuscles: ['Rhomboids', 'Latissimus Dorsi'],
    secondaryMuscles: ['Biceps Brachii', 'Rear Deltoid', 'Trapezius'],
    stabilizerMuscles: ['Erector Spinae', 'Core'],
    equipment: 'Cable Machine, V-Bar',
    difficulty: 'beginner',
    technique: [
      'Sit at the cable row station, feet flat on the platform, knees slightly bent.',
      'Grip the V-bar handle and sit upright with a neutral spine.',
      'Pull the handle toward your lower abdomen, driving elbows back and squeezing the shoulder blades.',
      'Hold for one count at full contraction.',
      'Extend your arms forward under control, allowing a slight forward lean to stretch the lats, then return to upright.',
    ],
    tips: [
      'Keep your torso nearly vertical—minimize swinging to isolate the back.',
      'Initiate each rep by retracting the shoulder blades before bending the elbows.',
      'A close neutral grip (V-bar) emphasizes the lower lats; a wide grip targets upper back more.',
    ],
    commonMistakes: [
      'Swinging the torso to generate momentum.',
      'Rounding the lower back at the end of the eccentric phase.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=GZbfZ033f74',
    alternatives: ['deadlift', 'pull_up', 'barbell_row', 'lat_pulldown', 'face_pull'],
  },
  {
    id: 'face_pull',
    name: 'Face Pull',
    category: 'back',
    primaryMuscles: ['Rear Deltoid', 'Trapezius (Mid/Lower)'],
    secondaryMuscles: ['Rhomboids', 'Rotator Cuff'],
    stabilizerMuscles: ['Core', 'Biceps Brachii'],
    equipment: 'Cable Machine, Rope Attachment',
    difficulty: 'beginner',
    technique: [
      'Set the cable pulley at upper chest to face height; attach a rope handle.',
      'Grab the rope with both hands (palms facing in) and step back to create tension.',
      'Pull the rope toward your face, splitting the rope ends to either side of your head.',
      'At peak contraction, externally rotate your shoulders so your hands point to the ceiling.',
      'Slowly return to the starting position under control.',
    ],
    tips: [
      'Lead with your elbows—keep them at or above shoulder height throughout.',
      'Perform with higher reps (15–25) to build shoulder health and posture.',
      'Use light weight; this is a corrective and hypertrophy exercise, not a strength test.',
    ],
    commonMistakes: [
      'Using too much weight, causing the elbows to drop below shoulder height.',
      'Skipping the external rotation at the top, missing the primary benefit.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=V8dZ3pyiCBo',
    alternatives: ['deadlift', 'pull_up', 'barbell_row', 'lat_pulldown', 'seated_cable_row'],
  },

  // ─── SHOULDERS ────────────────────────────────────────────────────────────
  {
    id: 'overhead_press',
    name: 'Overhead Press',
    category: 'shoulders',
    primaryMuscles: ['Anterior Deltoid', 'Medial Deltoid'],
    secondaryMuscles: ['Triceps Brachii', 'Upper Trapezius'],
    stabilizerMuscles: ['Core', 'Rotator Cuff', 'Serratus Anterior'],
    equipment: 'Barbell',
    difficulty: 'intermediate',
    technique: [
      'Set the bar at upper chest height in a rack; grip just outside shoulder width.',
      'Unrack the bar to your front rack position—bar resting on upper chest/anterior delts.',
      'Brace your core and glutes; press the bar straight up, slightly back at the top.',
      'As the bar passes your face, drive your head through to lock out with ears in line with arms.',
      'Lower the bar back to the front rack under control for the next rep.',
    ],
    tips: [
      '"Push your face through the window" at the top to achieve full lockout.',
      'Squeeze your glutes to prevent excessive lower back extension.',
      'Keep the bar over your mid-foot—a vertical bar path is most efficient.',
    ],
    commonMistakes: [
      'Pressing in front of the body rather than in a straight line overhead.',
      'Hyperextending the lower back to compensate for limited shoulder mobility.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=2yjwXTZQDDI',
    alternatives: ['lateral_raise', 'front_raise', 'rear_delt_fly', 'arnold_press'],
  },
  {
    id: 'lateral_raise',
    name: 'Lateral Raise',
    category: 'shoulders',
    primaryMuscles: ['Medial Deltoid'],
    secondaryMuscles: ['Anterior Deltoid', 'Supraspinatus'],
    stabilizerMuscles: ['Trapezius', 'Serratus Anterior'],
    equipment: 'Dumbbells',
    difficulty: 'beginner',
    technique: [
      'Stand with feet shoulder-width apart, holding dumbbells at your sides with a slight elbow bend.',
      'Raise both arms simultaneously out to the sides, leading with the elbows.',
      'Stop when your upper arms are parallel to the floor (at shoulder height).',
      'Tilt the front of the dumbbell slightly down (as if pouring a pitcher) to maximize medial delt activation.',
      'Lower the dumbbells slowly over 3–4 seconds back to the starting position.',
    ],
    tips: [
      'Use lighter weight and strict form—momentum removes the stimulus from the delts.',
      'A cable lateral raise provides constant tension throughout the range of motion.',
      'Stop at parallel—going higher can impinge the shoulder.',
    ],
    commonMistakes: [
      'Swinging the torso to heave the dumbbells up.',
      'Shrugging the traps, which shifts load away from the medial delt.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
    alternatives: ['overhead_press', 'front_raise', 'rear_delt_fly', 'arnold_press'],
  },
  {
    id: 'front_raise',
    name: 'Front Raise',
    category: 'shoulders',
    primaryMuscles: ['Anterior Deltoid'],
    secondaryMuscles: ['Medial Deltoid', 'Upper Pectoralis'],
    stabilizerMuscles: ['Core', 'Trapezius'],
    equipment: 'Dumbbells',
    difficulty: 'beginner',
    technique: [
      'Stand with feet hip-width, dumbbells in front of your thighs, palms facing back.',
      'Keeping a slight bend in the elbows, raise one (or both) dumbbells straight in front of you.',
      'Lift until the arm is parallel to the floor or just above shoulder height.',
      'Pause for one count, then lower under control back to the starting position.',
      'Alternate arms or perform simultaneously depending on preference.',
    ],
    tips: [
      'Avoid leaning back or swinging at the top—use a weight that allows strict form.',
      'A neutral (hammer) grip reduces impingement compared to a pronated grip.',
      'Since the anterior delt is already worked heavily by pressing, this exercise is often supplementary.',
    ],
    commonMistakes: [
      'Using too much body English to swing the weights up.',
      'Letting the arms cross the midline, shifting load to the upper chest.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=gkpBPNvCnig',
    alternatives: ['overhead_press', 'lateral_raise', 'rear_delt_fly', 'arnold_press'],
  },
  {
    id: 'rear_delt_fly',
    name: 'Rear Delt Fly',
    category: 'shoulders',
    primaryMuscles: ['Posterior Deltoid'],
    secondaryMuscles: ['Rhomboids', 'Trapezius (Middle)'],
    stabilizerMuscles: ['Rotator Cuff', 'Core'],
    equipment: 'Dumbbells',
    difficulty: 'beginner',
    technique: [
      'Sit at the end of a bench and hinge forward until your chest is close to your thighs.',
      'Hold dumbbells under your legs with a neutral grip, elbows slightly bent.',
      'Raise your arms out to the sides in a wide arc, leading with the elbows.',
      'Lift until your upper arms are parallel to the floor and your elbows are at shoulder height.',
      'Squeeze the rear delts, then lower slowly back to the starting position.',
    ],
    tips: [
      'Keep the neck neutral—look at a spot on the floor during the movement.',
      'Higher rep ranges (15–20) with lighter weight are more effective for rear delts.',
      'Can also be done standing with a pronounced hip hinge or on a reverse pec deck machine.',
    ],
    commonMistakes: [
      'Lifting the torso up during the movement, reducing rear delt isolation.',
      'Bending the elbows too much, engaging the biceps and rhomboids instead.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=EA7u4Q_8HQ0',
    alternatives: ['overhead_press', 'lateral_raise', 'front_raise', 'arnold_press'],
  },
  {
    id: 'arnold_press',
    name: 'Arnold Press',
    category: 'shoulders',
    primaryMuscles: ['Anterior Deltoid', 'Medial Deltoid'],
    secondaryMuscles: ['Posterior Deltoid', 'Triceps Brachii'],
    stabilizerMuscles: ['Rotator Cuff', 'Core'],
    equipment: 'Dumbbells',
    difficulty: 'intermediate',
    technique: [
      'Sit on a bench with back support, holding dumbbells at shoulder height, palms facing you.',
      'Press the dumbbells up while simultaneously rotating your palms forward (pronating).',
      'At the top, arms should be fully extended with palms facing away from you.',
      'Reverse the motion on the way down—pronate back to the starting position as you lower.',
      'Perform the rotation smoothly throughout the full range of motion.',
    ],
    tips: [
      'The rotation recruits all three deltoid heads across the movement arc.',
      'Use a controlled tempo; the rotation adds complexity that demands focus.',
      'Start lighter than your standard dumbbell press to master the rotation pattern.',
    ],
    commonMistakes: [
      'Only partially rotating the wrists, losing the added deltoid recruitment.',
      'Using momentum by bouncing at the bottom of the rep.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=68UNleGSoSI',
    alternatives: ['overhead_press', 'lateral_raise', 'front_raise', 'rear_delt_fly'],
  },

  // ─── BICEPS ───────────────────────────────────────────────────────────────
  {
    id: 'barbell_curl',
    name: 'Barbell Curl',
    category: 'biceps',
    primaryMuscles: ['Biceps Brachii'],
    secondaryMuscles: ['Brachialis', 'Brachioradialis'],
    stabilizerMuscles: ['Core', 'Anterior Deltoid'],
    equipment: 'Barbell or EZ-Bar',
    difficulty: 'beginner',
    technique: [
      'Stand with feet hip-width, holding the barbell with a supinated (underhand) grip at hip height.',
      'Pin your elbows to your sides and keep them there throughout the set.',
      'Curl the bar upward in an arc by flexing the elbow, bringing the bar to upper chest level.',
      'Squeeze the biceps hard at the top, with elbows slightly in front of your torso.',
      'Lower the bar slowly (3 seconds) back to full extension, feeling the stretch at the bottom.',
    ],
    tips: [
      'Initiate the curl by supinating (twisting) the wrists outward slightly at the top.',
      'An EZ-bar reduces wrist stress if straight bar curls cause discomfort.',
      'Keep your back straight—resist the temptation to lean back.',
    ],
    commonMistakes: [
      'Swinging the torso backward to heave the weight up.',
      'Not reaching full extension at the bottom, limiting the range of motion.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=ykJmrZ5v0Oo',
    alternatives: ['hammer_curl', 'incline_dumbbell_curl', 'concentration_curl'],
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    category: 'biceps',
    primaryMuscles: ['Brachialis', 'Brachioradialis'],
    secondaryMuscles: ['Biceps Brachii'],
    stabilizerMuscles: ['Core', 'Forearm Flexors'],
    equipment: 'Dumbbells',
    difficulty: 'beginner',
    technique: [
      'Stand with feet shoulder-width, holding dumbbells at your sides with a neutral grip (palms facing each other).',
      'Pin your elbows to your sides.',
      'Curl both dumbbells upward simultaneously (or alternate), keeping the neutral wrist position.',
      'Bring the dumbbells to shoulder level, squeezing the brachialis at the top.',
      'Lower under control to full extension.',
    ],
    tips: [
      'Keep the neutral grip throughout—do not supinate at the top.',
      'Can be performed alternating for better mind-muscle connection.',
      'Hammer curls also build forearm thickness via brachioradialis development.',
    ],
    commonMistakes: [
      'Rotating the wrist to supinate at the top, converting it to a standard curl.',
      'Letting the elbows drift forward, reducing brachialis isolation.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=zC3nLlEvin4',
    alternatives: ['barbell_curl', 'incline_dumbbell_curl', 'concentration_curl'],
  },
  {
    id: 'incline_dumbbell_curl',
    name: 'Incline Dumbbell Curl',
    category: 'biceps',
    primaryMuscles: ['Biceps Brachii (Long Head)'],
    secondaryMuscles: ['Brachialis', 'Brachioradialis'],
    stabilizerMuscles: ['Core', 'Rotator Cuff'],
    equipment: 'Dumbbells, Incline Bench',
    difficulty: 'intermediate',
    technique: [
      'Set the bench to 45–60° and sit back against it, letting the dumbbells hang straight down.',
      'The incline position pre-stretches the long head of the biceps.',
      'Curl both dumbbells up with a supinated grip, keeping elbows back against the bench.',
      'Squeeze at the top and lower back to full extension for maximum stretch.',
      'Avoid letting the elbows swing forward—keep them pinned behind your torso.',
    ],
    tips: [
      'The incline position is one of the best ways to target the long head and the peak of the bicep.',
      'Use a lighter weight than standard curls due to the mechanical disadvantage.',
      'Perform the movement slowly to maximize time under tension.',
    ],
    commonMistakes: [
      'Letting the elbows drift forward off the bench, removing the stretch benefit.',
      'Using too much weight and cutting the range of motion short.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=soxrZlIl35U',
    alternatives: ['barbell_curl', 'hammer_curl', 'concentration_curl'],
  },
  {
    id: 'concentration_curl',
    name: 'Concentration Curl',
    category: 'biceps',
    primaryMuscles: ['Biceps Brachii (Short Head)'],
    secondaryMuscles: ['Brachialis'],
    stabilizerMuscles: ['Core'],
    equipment: 'Dumbbell',
    difficulty: 'beginner',
    technique: [
      'Sit on a bench, lean forward slightly, and brace the back of your working elbow against your inner thigh.',
      `Hold a dumbbell with a supinated grip and let it hang at arm's length.`,
      'Curl the dumbbell upward, rotating the wrist slightly outward at the top for peak contraction.',
      'Squeeze hard at the top for one count.',
      'Lower slowly back to full extension, feeling the bicep stretch.',
    ],
    tips: [
      'This is a pure isolation move—use a weight you can control throughout.',
      'The braced elbow position eliminates cheating and maximizes bicep activation.',
      'Focus on the mind-muscle connection rather than moving heavy weight.',
    ],
    commonMistakes: [
      'Raising the elbow off the thigh, introducing shoulder and momentum.',
      'Rushing the eccentric (lowering) phase.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=0AUGkch3tzc',
    alternatives: ['barbell_curl', 'hammer_curl', 'incline_dumbbell_curl'],
  },

  // ─── TRICEPS ──────────────────────────────────────────────────────────────
  {
    id: 'tricep_pushdown',
    name: 'Tricep Pushdown',
    category: 'triceps',
    primaryMuscles: ['Triceps Brachii (Lateral Head)'],
    secondaryMuscles: ['Triceps Brachii (Medial Head)'],
    stabilizerMuscles: ['Core', 'Anconeus'],
    equipment: 'Cable Machine, Straight Bar or Rope',
    difficulty: 'beginner',
    technique: [
      'Set the cable pulley to the highest position and attach a straight bar or rope.',
      'Stand facing the machine, grip the attachment with a pronated grip, elbows at your sides.',
      'Keeping elbows pinned to your sides, push the bar down until your arms are fully extended.',
      'Squeeze the triceps hard at lockout for one count.',
      'Allow the weight to pull the bar back up slowly until your forearms are parallel to the floor.',
    ],
    tips: [
      'Keep elbows stationary—they act as a hinge point, not a lever.',
      'A rope attachment allows you to flare the handles at the bottom for greater contraction.',
      'Slight forward lean at the torso can allow for heavier loads while maintaining elbow position.',
    ],
    commonMistakes: [
      'Letting the elbows drift forward and upward during the lift.',
      'Using momentum by rocking the torso.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=vB5OHsJ3EME',
    alternatives: ['skull_crusher', 'overhead_tricep_extension', 'close_grip_bench'],
  },
  {
    id: 'skull_crusher',
    name: 'Skull Crusher',
    category: 'triceps',
    primaryMuscles: ['Triceps Brachii (Long Head)'],
    secondaryMuscles: ['Triceps Brachii (Lateral Head)', 'Anconeus'],
    stabilizerMuscles: ['Core', 'Shoulder Stabilizers'],
    equipment: 'EZ-Bar or Barbell, Bench',
    difficulty: 'intermediate',
    technique: [
      `Lie on a flat bench and press an EZ-bar to arm's length above your chest.`,
      'Keep upper arms vertical and perpendicular to the floor throughout.',
      'Slowly lower the bar by bending only at the elbows, bringing the bar toward your forehead.',
      'Stop just before the bar reaches your forehead, then extend back to the starting position.',
      'Keep elbows as close together as possible—avoid flaring outward.',
    ],
    tips: [
      'The EZ-bar version is easier on the wrists than a straight bar.',
      'Allow the elbows to track slightly back at the bottom to keep the long head under stretch.',
      'Use a spotter or keep the weight conservative—losing control here is dangerous.',
    ],
    commonMistakes: [
      'Letting the elbows flare wide, reducing tricep isolation.',
      'Lowering too fast and losing control at the bottom.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=d_KZxkY_0cM',
    alternatives: ['tricep_pushdown', 'overhead_tricep_extension', 'close_grip_bench'],
  },
  {
    id: 'overhead_tricep_extension',
    name: 'Overhead Tricep Extension',
    category: 'triceps',
    primaryMuscles: ['Triceps Brachii (Long Head)'],
    secondaryMuscles: ['Triceps Brachii (Medial Head)'],
    stabilizerMuscles: ['Core', 'Anterior Deltoid'],
    equipment: 'Dumbbell or Cable',
    difficulty: 'beginner',
    technique: [
      'Stand or sit holding a single dumbbell with both hands overhead, arms fully extended.',
      'Grip the top plate of the dumbbell with palms facing up and thumbs around the handle.',
      'Keep upper arms vertical and close to your ears throughout.',
      'Lower the dumbbell behind your head by bending at the elbows until you feel a deep stretch.',
      'Extend back to full lockout, squeezing the triceps at the top.',
    ],
    tips: [
      'The overhead position maximizes the long head stretch—the most undertrained tricep head.',
      'Keep the core tight and avoid arching the lower back.',
      'A cable version provides constant tension and is easier on the elbows for some individuals.',
    ],
    commonMistakes: [
      'Letting the elbows flare out to the sides instead of staying close to the head.',
      'Using too much weight, causing the lower back to excessively arch.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=YbX7Wd8jQ-Q',
    alternatives: ['tricep_pushdown', 'skull_crusher', 'close_grip_bench'],
  },
  {
    id: 'close_grip_bench',
    name: 'Close-Grip Bench Press',
    category: 'triceps',
    primaryMuscles: ['Triceps Brachii'],
    secondaryMuscles: ['Pectoralis Major', 'Anterior Deltoid'],
    stabilizerMuscles: ['Rotator Cuff', 'Core'],
    equipment: 'Barbell, Bench',
    difficulty: 'intermediate',
    technique: [
      'Lie on a flat bench and grip the bar with hands shoulder-width apart (narrower than a standard bench press).',
      'Unrack the bar and hold it directly above your chest.',
      'Lower the bar to your lower chest, keeping elbows tucked close to your torso.',
      'Press the bar back to full lockout, squeezing the triceps.',
      'Do not use a very narrow grip (hands touching)—shoulder-width is optimal.',
    ],
    tips: [
      'Shoulder-width grip is ideal; an extremely narrow grip stresses the wrists.',
      'Focus on keeping elbows close to the body to maximize tricep engagement.',
      'This is also a great movement for building overall pressing strength.',
    ],
    commonMistakes: [
      'Gripping too narrow, which strains the wrists and reduces stability.',
      'Letting the elbows flare outward, shifting the load to the chest.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=nEF0bv2FW94',
    alternatives: ['tricep_pushdown', 'skull_crusher', 'overhead_tricep_extension'],
  },

  // ─── LEGS ─────────────────────────────────────────────────────────────────
  {
    id: 'squat',
    name: 'Barbell Back Squat',
    category: 'legs',
    primaryMuscles: ['Quadriceps', 'Glutes'],
    secondaryMuscles: ['Hamstrings', 'Adductors', 'Erector Spinae'],
    stabilizerMuscles: ['Core', 'Calves'],
    equipment: 'Barbell, Squat Rack',
    difficulty: 'advanced',
    technique: [
      'Set the bar across your upper traps (high bar) or rear delts (low bar); unrack with feet shoulder-width apart.',
      'Take a deep breath and brace your core 360° before initiating the descent.',
      'Break at the hips and knees simultaneously, keeping the chest up and knees tracking over toes.',
      'Descend until the hip crease is at or below the top of the knee (below parallel).',
      'Drive through the whole foot, pushing the floor away, to return to the starting position.',
    ],
    tips: [
      '"Spread the floor" with your feet to activate the glutes and maintain knee alignment.',
      'Keep the bar over your mid-foot throughout the movement.',
      `Brace as if you're about to take a punch to the gut for spinal safety.`,
    ],
    commonMistakes: [
      'Caving the knees inward (valgus collapse) at the bottom of the squat.',
      'Excessive forward lean causing the torso to fold over.',
      'Bouncing out of the hole rather than using muscle strength.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=Dy28eq2PjcM',
    alternatives: ['leg_press', 'romanian_deadlift', 'leg_curl', 'leg_extension', 'walking_lunge', 'calf_raise'],
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    category: 'legs',
    primaryMuscles: ['Quadriceps', 'Glutes'],
    secondaryMuscles: ['Hamstrings', 'Adductors'],
    stabilizerMuscles: ['Core'],
    equipment: 'Leg Press Machine',
    difficulty: 'beginner',
    technique: [
      'Sit in the leg press machine with your back flat against the pad.',
      'Place feet shoulder-width apart in the middle of the platform.',
      'Release the safety handles and lower the platform by bending the knees toward your chest.',
      'Stop before the lower back rounds (approximately 90° knee angle).',
      'Press through the entire foot to extend your legs, stopping just short of full lockout.',
    ],
    tips: [
      'Higher foot placement emphasizes the glutes and hamstrings; lower placement targets the quads.',
      'Do not lock out the knees explosively at the top—keep tension on the muscles.',
      'Avoid placing your hands on your knees to assist the movement.',
    ],
    commonMistakes: [
      'Allowing the lower back to round off the pad at the bottom.',
      'Locking out the knees fully under load, which stresses the joint.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=IZxyjW7MPJQ',
    alternatives: ['squat', 'romanian_deadlift', 'leg_curl', 'leg_extension', 'walking_lunge', 'calf_raise'],
  },
  {
    id: 'romanian_deadlift',
    name: 'Romanian Deadlift',
    category: 'legs',
    primaryMuscles: ['Hamstrings', 'Glutes'],
    secondaryMuscles: ['Erector Spinae', 'Adductors'],
    stabilizerMuscles: ['Core', 'Forearms'],
    equipment: 'Barbell or Dumbbells',
    difficulty: 'intermediate',
    technique: [
      'Stand with feet hip-width, holding the bar at hip height with a pronated or mixed grip.',
      'Maintain a slight bend in the knees and a neutral spine throughout.',
      'Hinge at the hips, pushing them back as you lower the bar along the front of your legs.',
      'Lower until you feel a strong stretch in the hamstrings (typically mid-shin level).',
      'Drive the hips forward to return to standing, squeezing the glutes at the top.',
    ],
    tips: [
      'Think of "closing a car door with your hip" to initiate the hinge correctly.',
      'Keep the bar in contact with your legs the entire way down.',
      'The range of motion is limited by hamstring flexibility—do not round the lower back to go lower.',
    ],
    commonMistakes: [
      'Bending the knees too much, turning it into a conventional deadlift.',
      'Rounding the lower back, especially as the weight gets heavier.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
    alternatives: ['squat', 'leg_press', 'leg_curl', 'leg_extension', 'walking_lunge', 'calf_raise'],
  },
  {
    id: 'leg_curl',
    name: 'Lying Leg Curl',
    category: 'legs',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: ['Gastrocnemius', 'Popliteus'],
    stabilizerMuscles: ['Core', 'Glutes'],
    equipment: 'Leg Curl Machine',
    difficulty: 'beginner',
    technique: [
      'Lie face down on the machine, aligning the pad just below your calves.',
      'Grip the handles and press your hips firmly into the bench.',
      'Curl the pad toward your glutes by flexing the knees as far as the machine allows.',
      'Hold the contracted position for one count, squeezing the hamstrings.',
      'Lower the pad slowly to the starting position for maximum eccentric loading.',
    ],
    tips: [
      'Plantarflex (point) the feet at the top to maximize hamstring contraction.',
      'The seated leg curl is a great alternative that provides better hip-flexed stretch on the hamstrings.',
      'Eccentric-focused reps (slow lowering) are highly effective for hamstring hypertrophy.',
    ],
    commonMistakes: [
      'Lifting the hips off the pad to get more range of motion.',
      'Using momentum to swing the weight up.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=1Tq3QdYUuHs',
    alternatives: ['squat', 'leg_press', 'romanian_deadlift', 'leg_extension', 'walking_lunge', 'calf_raise'],
  },
  {
    id: 'leg_extension',
    name: 'Leg Extension',
    category: 'legs',
    primaryMuscles: ['Quadriceps'],
    secondaryMuscles: ['Rectus Femoris'],
    stabilizerMuscles: ['Core'],
    equipment: 'Leg Extension Machine',
    difficulty: 'beginner',
    technique: [
      'Sit in the leg extension machine with the pad resting on the front of your ankles.',
      `Adjust the seat so the knee joint aligns with the machine's pivot point.`,
      'Grip the handles and extend your legs to fully straighten them.',
      'Hold the top position for one count with the quads fully contracted.',
      'Lower the pad slowly back to the starting position (90° knee angle).',
    ],
    tips: [
      'Point the toes slightly upward (dorsiflexion) to increase quad activation.',
      'Use slow, controlled repetitions—this is an isolation exercise, not for heavy loading.',
      'Pause at full extension to maximize the peak contraction.',
    ],
    commonMistakes: [
      'Using excessive weight that causes the lower back to lift off the pad.',
      'Allowing the weight to drop rapidly on the eccentric phase.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=YyvSfVjQeL0',
    alternatives: ['squat', 'leg_press', 'romanian_deadlift', 'leg_curl', 'walking_lunge', 'calf_raise'],
  },
  {
    id: 'walking_lunge',
    name: 'Walking Lunge',
    category: 'legs',
    primaryMuscles: ['Quadriceps', 'Glutes'],
    secondaryMuscles: ['Hamstrings', 'Adductors', 'Calves'],
    stabilizerMuscles: ['Core', 'Hip Abductors'],
    equipment: 'Bodyweight or Dumbbells',
    difficulty: 'beginner',
    technique: [
      'Stand with feet together, holding dumbbells at your sides (or hands on hips for bodyweight).',
      'Step forward with one foot, lowering your back knee toward the floor.',
      'The front knee should be directly above the ankle; the rear knee hovers an inch from the floor.',
      'Drive through the front heel to stand, then bring the rear foot forward to meet the front foot.',
      'Alternate legs and continue walking forward.',
    ],
    tips: [
      'Keep your torso upright—do not lean excessively forward.',
      'Take a long enough stride so the front shin remains vertical at the bottom.',
      'Add a slight pause at the bottom to increase difficulty and remove momentum.',
    ],
    commonMistakes: [
      'Allowing the front knee to cave inward (knee valgus).',
      'Taking too short a stride, causing the front knee to travel excessively past the toes.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=L8fvypPrzzs',
    alternatives: ['squat', 'leg_press', 'romanian_deadlift', 'leg_curl', 'leg_extension', 'calf_raise'],
  },
  {
    id: 'calf_raise',
    name: 'Standing Calf Raise',
    category: 'legs',
    primaryMuscles: ['Gastrocnemius'],
    secondaryMuscles: ['Soleus'],
    stabilizerMuscles: ['Core', 'Tibialis Anterior'],
    equipment: 'Calf Raise Machine or Step',
    difficulty: 'beginner',
    technique: [
      'Stand with the balls of your feet on a raised platform, heels hanging off the edge.',
      'Lower your heels as far as possible for a full stretch of the calf.',
      'Rise onto your toes as high as possible, squeezing the gastrocnemius at the top.',
      'Hold the peak contraction for one count.',
      'Lower slowly back to the starting stretch position.',
    ],
    tips: [
      'Use the full range of motion—the stretch at the bottom is as important as the contraction.',
      'Seated calf raises (knees bent) target the soleus more effectively.',
      'High rep sets (15–25) are often more effective for calf hypertrophy.',
    ],
    commonMistakes: [
      `Bouncing at the bottom, using the Achilles tendon's elastic recoil instead of muscle work.`,
      'Not reaching full range of motion in both directions.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=gwLzBJYoWlI',
    alternatives: ['squat', 'leg_press', 'romanian_deadlift', 'leg_curl', 'leg_extension', 'walking_lunge'],
  },

  // ─── GLUTES ───────────────────────────────────────────────────────────────
  {
    id: 'hip_thrust',
    name: 'Hip Thrust',
    category: 'glutes',
    primaryMuscles: ['Gluteus Maximus'],
    secondaryMuscles: ['Hamstrings', 'Adductors'],
    stabilizerMuscles: ['Core', 'Quadriceps'],
    equipment: 'Barbell, Bench',
    difficulty: 'intermediate',
    technique: [
      'Sit on the floor with your upper back against a bench; roll a barbell over your hips.',
      'Place feet flat on the floor, hip-width apart, knees bent at ~90°.',
      'Drive through the heels to thrust the hips upward, squeezing the glutes at the top.',
      'At the top, your shins should be vertical and your torso should be parallel to the floor.',
      'Lower the hips slowly back to the floor and repeat.',
    ],
    tips: [
      'Use a barbell pad to protect your hip bones from the bar.',
      'Tuck your chin to maintain a neutral spine at the top of the movement.',
      'Push your knees outward slightly throughout the movement to maximize glute activation.',
    ],
    commonMistakes: [
      'Hyperextending the lower back at the top, using lumbar extension instead of glute contraction.',
      'Placing feet too far from the body, shifting the load to the hamstrings.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=SEdqd1n0cvg',
    alternatives: ['glute_bridge', 'bulgarian_split_squat', 'cable_kickback'],
  },
  {
    id: 'glute_bridge',
    name: 'Glute Bridge',
    category: 'glutes',
    primaryMuscles: ['Gluteus Maximus'],
    secondaryMuscles: ['Hamstrings', 'Core'],
    stabilizerMuscles: ['Transverse Abdominis', 'Adductors'],
    equipment: 'Bodyweight or Dumbbell',
    difficulty: 'beginner',
    technique: [
      'Lie on your back with knees bent, feet flat on the floor hip-width apart.',
      'Place a dumbbell or weight plate across your hips (optional for added resistance).',
      'Brace your core and drive through your heels to lift your hips toward the ceiling.',
      'Squeeze the glutes hard at the top until your body forms a straight line from knees to shoulders.',
      'Lower your hips back to the floor in a controlled manner.',
    ],
    tips: [
      'At the top, your knees, hips, and shoulders should form a straight diagonal line.',
      'Use a slow 2-second hold at the top to ensure glute engagement over lumbar extension.',
      'Progress to hip thrusts once the glute bridge becomes too easy.',
    ],
    commonMistakes: [
      'Pushing through the toes rather than the heels, activating quads over glutes.',
      'Arching the lower back at the top rather than squeezing the glutes.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=OUgsJ8-Vi0E',
    alternatives: ['hip_thrust', 'bulgarian_split_squat', 'cable_kickback'],
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    category: 'glutes',
    primaryMuscles: ['Gluteus Maximus', 'Quadriceps'],
    secondaryMuscles: ['Hamstrings', 'Adductors'],
    stabilizerMuscles: ['Core', 'Hip Flexors'],
    equipment: 'Dumbbells or Barbell, Bench',
    difficulty: 'intermediate',
    technique: [
      'Stand about two feet in front of a bench; place the top of one foot on the bench behind you.',
      'Hold dumbbells at your sides or a barbell across your back.',
      'Lower your rear knee toward the floor by bending the front knee.',
      'Keep your front shin vertical and your torso upright.',
      'Drive through the front heel to return to the starting position.',
    ],
    tips: [
      'The front foot distance determines the emphasis: farther forward = more glutes/hamstrings; closer = more quads.',
      'Keep your gaze forward and chest up to maintain torso position.',
      'This is one of the best single-leg exercises for glute development.',
    ],
    commonMistakes: [
      'Letting the front knee cave inward during the descent.',
      'Placing the back foot too high on the bench, causing hip flexor strain.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
    alternatives: ['hip_thrust', 'glute_bridge', 'cable_kickback'],
  },
  {
    id: 'cable_kickback',
    name: 'Cable Kickback',
    category: 'glutes',
    primaryMuscles: ['Gluteus Maximus'],
    secondaryMuscles: ['Hamstrings'],
    stabilizerMuscles: ['Core', 'Hip Abductors'],
    equipment: 'Cable Machine, Ankle Attachment',
    difficulty: 'beginner',
    technique: [
      'Attach an ankle cuff to the low pulley; attach it to one ankle.',
      'Face the machine, grasping it lightly for balance, with a slight forward lean.',
      'Keep the working knee slightly bent and kick the leg straight back by extending the hip.',
      'Squeeze the glute hard at full extension, holding for one count.',
      'Slowly return the leg to the starting position without letting the weight touch the stack.',
    ],
    tips: [
      'Focus on hip extension, not knee extension—the knee angle should remain constant.',
      'Avoid rotating the pelvis; keep hips level throughout the movement.',
      'Use a weight that allows full control throughout the range of motion.',
    ],
    commonMistakes: [
      'Swinging the leg using momentum rather than controlled glute contraction.',
      'Bending the knee to kick back, which involves the hamstrings more than the glutes.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=qKgNEzX_JFo',
    alternatives: ['hip_thrust', 'glute_bridge', 'bulgarian_split_squat'],
  },

  // ─── CORE ─────────────────────────────────────────────────────────────────
  {
    id: 'plank',
    name: 'Plank',
    category: 'core',
    primaryMuscles: ['Transverse Abdominis', 'Rectus Abdominis'],
    secondaryMuscles: ['Obliques', 'Erector Spinae'],
    stabilizerMuscles: ['Glutes', 'Shoulder Girdle'],
    equipment: 'Bodyweight',
    difficulty: 'beginner',
    technique: [
      'Place forearms on the floor with elbows under your shoulders; extend your legs behind you.',
      'Lift your hips so your body forms a straight line from head to heels.',
      'Brace your core by drawing the navel toward the spine and squeezing the glutes.',
      'Hold the position while breathing normally—do not hold your breath.',
      'Maintain a neutral neck—look at the floor, not forward.',
    ],
    tips: [
      'Think of the plank as an active hold, not a passive rest—squeeze everything.',
      'Progress to weighted planks, RKC planks, or plank variations once 60 seconds feels easy.',
      'Avoid letting the hips rise into a pike or sag toward the floor.',
    ],
    commonMistakes: [
      'Allowing the hips to sag, reducing core engagement and straining the lower back.',
      'Raising the hips too high, which reduces abdominal tension.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=pSHjTRCQxIw',
    alternatives: ['crunch', 'russian_twist', 'hanging_leg_raise', 'ab_wheel_rollout'],
  },
  {
    id: 'crunch',
    name: 'Crunch',
    category: 'core',
    primaryMuscles: ['Rectus Abdominis'],
    secondaryMuscles: ['Obliques'],
    stabilizerMuscles: ['Hip Flexors', 'Transverse Abdominis'],
    equipment: 'Bodyweight',
    difficulty: 'beginner',
    technique: [
      'Lie on your back with knees bent and feet flat on the floor.',
      'Place fingertips lightly behind your ears—do not pull on your neck.',
      'Contract your abs and curl your shoulder blades off the floor.',
      'At the top, exhale fully and hold for one count with a strong abdominal squeeze.',
      'Lower your shoulders slowly back to the floor without fully relaxing the abs.',
    ],
    tips: [
      'The range of motion is small—only the shoulder blades lift, not the lower back.',
      'Focus on the contraction, not the height of the movement.',
      'Add a cable crunch or decline crunch for progressive overload.',
    ],
    commonMistakes: [
      'Pulling on the neck with the hands, straining the cervical spine.',
      'Using the hip flexors to lift the torso instead of the abdominals.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=Xyd_fa5zoEU',
    alternatives: ['plank', 'russian_twist', 'hanging_leg_raise', 'ab_wheel_rollout'],
  },
  {
    id: 'russian_twist',
    name: 'Russian Twist',
    category: 'core',
    primaryMuscles: ['Obliques'],
    secondaryMuscles: ['Rectus Abdominis', 'Transverse Abdominis'],
    stabilizerMuscles: ['Hip Flexors', 'Erector Spinae'],
    equipment: 'Bodyweight or Weight Plate',
    difficulty: 'beginner',
    technique: [
      'Sit on the floor with knees bent, feet either flat or elevated (harder).',
      'Lean back slightly to create a V-shape between your torso and thighs.',
      'Hold a weight plate or medicine ball with both hands in front of your chest.',
      'Rotate your torso to the right, tapping the weight to the floor beside your hip.',
      'Rotate to the left and repeat, keeping core braced throughout.',
    ],
    tips: [
      'Rotate from the torso, not just the arms—feel the obliques driving the movement.',
      'Elevate the feet to increase core demand.',
      'Breathe out on each rotation; do not hold your breath.',
    ],
    commonMistakes: [
      'Swinging the arms side to side without rotating the torso.',
      'Rounding the lower back—maintain a slight lumbar curve throughout.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=wkD8rjkodUI',
    alternatives: ['plank', 'crunch', 'hanging_leg_raise', 'ab_wheel_rollout'],
  },
  {
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise',
    category: 'core',
    primaryMuscles: ['Rectus Abdominis (Lower)', 'Hip Flexors'],
    secondaryMuscles: ['Obliques', 'Transverse Abdominis'],
    stabilizerMuscles: ['Grip Muscles', 'Shoulder Girdle'],
    equipment: 'Pull-Up Bar',
    difficulty: 'intermediate',
    technique: [
      'Hang from a pull-up bar with an overhand grip, arms fully extended.',
      'Brace your core and press your lower back into a neutral or slightly flexed position.',
      'Raise both legs by flexing at the hip and drawing the knees toward the chest (easier) or keeping legs straight (harder).',
      'Lift until your thighs are parallel to the floor or higher for a full range of motion.',
      'Lower legs slowly back to the hanging position under control.',
    ],
    tips: [
      'Avoid swinging—initiate each rep from a dead hang.',
      'Exhale as you raise the legs; this assists abdominal contraction.',
      'Straight-leg version dramatically increases difficulty and lower ab demand.',
    ],
    commonMistakes: [
      'Using momentum by swinging the legs back before raising them.',
      'Not completing the posterior pelvic tilt, limiting lower abdominal activation.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=Pr1ieGZ5atk',
    alternatives: ['plank', 'crunch', 'russian_twist', 'ab_wheel_rollout'],
  },
  {
    id: 'ab_wheel_rollout',
    name: 'Ab Wheel Rollout',
    category: 'core',
    primaryMuscles: ['Rectus Abdominis', 'Transverse Abdominis'],
    secondaryMuscles: ['Obliques', 'Latissimus Dorsi'],
    stabilizerMuscles: ['Erector Spinae', 'Shoulder Stabilizers'],
    equipment: 'Ab Wheel',
    difficulty: 'advanced',
    technique: [
      'Kneel on the floor and grip the ab wheel with both hands directly below your shoulders.',
      'Brace the core hard—this is critical to protect the lower back.',
      'Roll the wheel forward by extending your arms, keeping hips low and back flat.',
      'Extend as far as you can while maintaining a neutral spine—do not let the hips sag.',
      'Contract the abs to pull the wheel back to the starting position under control.',
    ],
    tips: [
      'Start with partial rollouts if full rollouts cause lower back pain.',
      'Think of it as an extended plank—the core must be rigid at all times.',
      'This is one of the most challenging core exercises—progress carefully.',
    ],
    commonMistakes: [
      'Allowing the hips to sag, causing excessive lumbar extension and lower back strain.',
      'Using the arms and lats to pull back rather than contracting the abs.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=0a1FLKJB2WY',
    alternatives: ['plank', 'crunch', 'russian_twist', 'hanging_leg_raise'],
  },

  // ─── CARDIO ───────────────────────────────────────────────────────────────
  {
    id: 'treadmill_run',
    name: 'Treadmill Run',
    category: 'cardio',
    primaryMuscles: ['Quadriceps', 'Hamstrings', 'Calves'],
    secondaryMuscles: ['Glutes', 'Hip Flexors'],
    stabilizerMuscles: ['Core', 'Tibialis Anterior'],
    equipment: 'Treadmill',
    difficulty: 'beginner',
    technique: [
      'Set the treadmill to a 1% incline to approximate outdoor running effort.',
      'Begin with a 5-minute brisk walking warm-up before increasing to a run.',
      'Land with a midfoot strike below your center of mass, not a heel strike in front.',
      'Keep your arms bent at ~90° and swing them forward-back, not across the body.',
      'Maintain an upright posture with a slight forward lean from the ankles.',
    ],
    tips: [
      'Use the 1% incline rule to offset the lack of air resistance on a treadmill.',
      'Keep your gaze forward, not down at your feet.',
      'For fat loss, a moderate pace sustained for 30–60 minutes is highly effective.',
    ],
    commonMistakes: [
      'Overstriding with a heavy heel strike, increasing injury risk.',
      'Holding the handrails, which reduces caloric expenditure and throws off gait.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=_kGESn8ArrU',
    alternatives: ['jump_rope', 'cycling', 'burpee'],
  },
  {
    id: 'jump_rope',
    name: 'Jump Rope',
    category: 'cardio',
    primaryMuscles: ['Calves', 'Quadriceps'],
    secondaryMuscles: ['Shoulders', 'Core'],
    stabilizerMuscles: ['Ankle Stabilizers', 'Hip Flexors'],
    equipment: 'Jump Rope',
    difficulty: 'beginner',
    technique: [
      'Hold the rope handles at your sides with elbows close to your body.',
      'Use small wrist circles to rotate the rope—the motion comes from the wrists, not the arms.',
      'Jump just high enough for the rope to pass under your feet (1–2 inches).',
      'Land softly on the balls of your feet with a slight knee bend to absorb impact.',
      'Maintain an upright posture throughout.',
    ],
    tips: [
      'Start with basic two-foot jumps before progressing to alternating feet or double-unders.',
      'Use a rope that reaches your armpits when stood upon.',
      'Jump rope is highly effective for cardiovascular conditioning and coordination.',
    ],
    commonMistakes: [
      'Jumping too high, wasting energy and increasing landing impact.',
      'Using large arm circles instead of wrist rotation.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=FJmRQ5iTXKE',
    alternatives: ['treadmill_run', 'cycling', 'burpee'],
  },
  {
    id: 'cycling',
    name: 'Stationary Bike / Cycling',
    category: 'cardio',
    primaryMuscles: ['Quadriceps', 'Hamstrings'],
    secondaryMuscles: ['Glutes', 'Calves'],
    stabilizerMuscles: ['Core', 'Hip Flexors'],
    equipment: 'Stationary Bike or Bicycle',
    difficulty: 'beginner',
    technique: [
      'Adjust the seat height so your knee has a slight bend (5–10°) at the bottom of the pedal stroke.',
      'Position the handlebars at a comfortable height to avoid straining the lower back.',
      'Maintain a cadence of 70–90 RPM for steady-state cardio.',
      'Push down and pull back through the pedal stroke for full leg engagement.',
      'Keep your core lightly engaged and avoid excessive rocking of the hips.',
    ],
    tips: [
      'Cycling is very low-impact and suitable for individuals with knee or joint issues.',
      'HIIT intervals on the bike (20s sprint / 40s rest) are highly time-efficient.',
      'A proper bike fit is crucial for both comfort and injury prevention.',
    ],
    commonMistakes: [
      'Setting the seat too low, increasing knee stress and reducing power output.',
      'Pedaling with only the quads and neglecting the hamstring pull-back.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=Jmwk3GQqhGo',
    alternatives: ['treadmill_run', 'jump_rope', 'burpee'],
  },
  {
    id: 'burpee',
    name: 'Burpee',
    category: 'cardio',
    primaryMuscles: ['Quadriceps', 'Chest', 'Shoulders'],
    secondaryMuscles: ['Core', 'Hamstrings', 'Triceps'],
    stabilizerMuscles: ['Glutes', 'Calves'],
    equipment: 'Bodyweight',
    difficulty: 'intermediate',
    technique: [
      'Stand with feet shoulder-width apart.',
      'Drop into a squat and place your hands on the floor just outside your feet.',
      'Jump your feet back simultaneously to land in a push-up position.',
      'Perform a push-up (optional but recommended for full-body engagement).',
      'Jump your feet forward to outside your hands, then explode upward with arms overhead.',
    ],
    tips: [
      'Keep each movement crisp and connected—avoid pausing between phases.',
      'Modify by stepping the feet back instead of jumping to reduce impact.',
      'Use burpees in HIIT workouts or as a finisher for intense calorie burn.',
    ],
    commonMistakes: [
      'Letting the hips sag in the plank position during the push-up.',
      'Not fully extending the hips on the jump, reducing power output.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=dZgVxmf6jkA',
    alternatives: ['treadmill_run', 'jump_rope', 'cycling'],
  },

  // ─── FULL BODY ────────────────────────────────────────────────────────────
  {
    id: 'clean_and_press',
    name: 'Clean and Press',
    category: 'full_body',
    primaryMuscles: ['Shoulders', 'Quadriceps', 'Trapezius'],
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Triceps', 'Core'],
    stabilizerMuscles: ['Forearms', 'Rotator Cuff', 'Erector Spinae'],
    equipment: 'Barbell or Dumbbells',
    difficulty: 'advanced',
    technique: [
      'Start with the bar on the floor in a deadlift-like setup: hip-width stance, neutral spine.',
      'Pull the bar explosively from the floor by extending the hips, knees, and ankles simultaneously.',
      'As the bar reaches hip height, shrug the traps and pull the elbows high and to the sides.',
      'Drop into a quarter squat and rotate the elbows around and under the bar to catch it in the front rack position.',
      'From the front rack, press the bar overhead to full lockout, then lower and return to the floor.',
    ],
    tips: [
      'Master the deadlift, power shrug, and overhead press independently before combining them.',
      'The clean is a pulling exercise—let momentum and technique carry the bar, not just arm strength.',
      'Pulling straps can help if grip is a limiting factor.',
    ],
    commonMistakes: [
      'Pulling with the arms too early rather than waiting for full hip extension.',
      'Catching the bar with stiff elbows, risking wrist and forearm injury.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=fkyIGNd-sno',
    alternatives: ['turkish_getup', 'thruster'],
  },
  {
    id: 'turkish_getup',
    name: 'Turkish Get-Up',
    category: 'full_body',
    primaryMuscles: ['Shoulders', 'Core', 'Glutes'],
    secondaryMuscles: ['Quadriceps', 'Hamstrings', 'Triceps'],
    stabilizerMuscles: ['Rotator Cuff', 'Hip Stabilizers', 'Forearms'],
    equipment: 'Kettlebell or Dumbbell',
    difficulty: 'advanced',
    technique: [
      'Lie on your back, holding a kettlebell in your right hand with arm extended toward the ceiling.',
      'Bend the right knee, foot flat on the floor; left arm extended 45° to the side.',
      'Roll to the right forearm, then to the right hand, then sweep the left leg back into a lunge position.',
      'Stand up fully with the kettlebell overhead, then reverse the sequence to return to the floor.',
      'Complete all reps on one side before switching.',
    ],
    tips: [
      'Start with no weight to learn the movement pattern before adding load.',
      'Keep your eyes on the kettlebell throughout—it acts as a cue for shoulder position.',
      'Each phase of the get-up is its own exercise; pause and reset if needed.',
    ],
    commonMistakes: [
      'Rushing through the movement phases instead of treating each as a distinct step.',
      'Losing shoulder packing at any point, risking a drop.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=0bWRPC49-KI',
    alternatives: ['clean_and_press', 'thruster'],
  },
  {
    id: 'thruster',
    name: 'Thruster',
    category: 'full_body',
    primaryMuscles: ['Quadriceps', 'Shoulders', 'Glutes'],
    secondaryMuscles: ['Triceps', 'Core', 'Hamstrings'],
    stabilizerMuscles: ['Rotator Cuff', 'Erector Spinae', 'Calves'],
    equipment: 'Barbell or Dumbbells',
    difficulty: 'advanced',
    technique: [
      'Start with the bar in the front rack position, feet shoulder-width apart.',
      'Perform a full front squat, descending until the hip crease is below the knee.',
      'Drive explosively out of the bottom of the squat.',
      'Use the upward momentum from the squat to initiate the overhead press.',
      'Press the bar to full lockout overhead at the top, then lower back to the front rack and repeat.',
    ],
    tips: [
      'The squat and press should feel like one fluid movement, not two separate exercises.',
      'Maintain an upright torso during the squat to keep the bar in the front rack.',
      'Used heavily in CrossFit—master the front squat and press separately first.',
    ],
    commonMistakes: [
      'Pausing at the top of the squat before pressing, breaking the fluidity and losing momentum.',
      'Letting the elbows drop during the front squat, causing the bar to roll forward.',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=ioHX_QCFkgA',
    alternatives: ['clean_and_press', 'turkish_getup'],
  },
];
