export type NutrientCategory = 'fat_vitamin' | 'water_vitamin' | 'macromineral' | 'trace_mineral';

export interface Micronutrient {
  id: string;
  name: string;
  altName?: string;
  category: NutrientCategory;
  emoji: string;
  role: string;
  deficiency: string[];
  sources: string[];
  rda: string;
  upperLimit?: string;
  tip?: string;
}

export const CATEGORY_LABELS: Record<NutrientCategory, string> = {
  fat_vitamin: 'Fat-Soluble Vitamins',
  water_vitamin: 'Water-Soluble Vitamins',
  macromineral: 'Macrominerals',
  trace_mineral: 'Trace Minerals',
};

export const MICRONUTRIENTS: Micronutrient[] = [
  // ─── Fat-Soluble Vitamins ───────────────────────────────────────────────
  {
    id: 'vit_a',
    name: 'Vitamin A',
    altName: 'Retinol',
    category: 'fat_vitamin',
    emoji: '🟠',
    role:
      'Essential for vision (especially night vision), immune function, skin integrity, and cellular differentiation. Also acts as an antioxidant in its provitamin A (beta-carotene) form.',
    deficiency: [
      'Night blindness and dry eyes (xerophthalmia)',
      'Increased susceptibility to infections',
      'Dry, rough skin and hair follicle plugging',
      'Poor wound healing',
      'Impaired growth in children',
    ],
    sources: [
      'Liver (beef, chicken)',
      'Salmon and mackerel',
      'Eggs',
      'Dairy (milk, cheese, butter)',
      'Sweet potato (beta-carotene)',
      'Carrots, pumpkin, butternut squash',
      'Dark leafy greens (spinach, kale)',
    ],
    rda: '700 mcg RAE/day (women) · 900 mcg RAE/day (men)',
    upperLimit: '3,000 mcg/day (preformed retinol)',
    tip: 'Pair orange and yellow vegetables with a small amount of fat — beta-carotene is fat-soluble and absorbed far better alongside dietary fat.',
  },
  {
    id: 'vit_d',
    name: 'Vitamin D',
    altName: 'Calciferol',
    category: 'fat_vitamin',
    emoji: '☀️',
    role:
      'Regulates calcium and phosphorus absorption for bone mineralisation, supports immune modulation, muscle function, and cardiovascular health. The skin synthesises it from UVB sunlight exposure.',
    deficiency: [
      'Rickets in children (soft, bowed bones)',
      'Osteomalacia (bone pain and muscle weakness) in adults',
      'Increased fracture risk and osteoporosis',
      'Fatigue and low mood / seasonal depression',
      'Frequent infections due to impaired immune function',
    ],
    sources: [
      'Sunlight (15–30 min daily skin exposure)',
      'Fatty fish (salmon, sardines, mackerel, tuna)',
      'Cod liver oil',
      'Egg yolks',
      'Fortified dairy and plant milks',
      'Fortified breakfast cereals',
      'Beef liver (small amounts)',
    ],
    rda: '600 IU/day (adults under 70) · 800 IU/day (adults over 70)',
    upperLimit: '4,000 IU/day',
    tip: 'Blood levels are the most reliable guide — aim for 25-OH-D serum levels of 40–60 ng/mL. Supplementing D3 (cholecalciferol) alongside K2 helps direct calcium to bones rather than arteries.',
  },
  {
    id: 'vit_e',
    name: 'Vitamin E',
    altName: 'Tocopherol',
    category: 'fat_vitamin',
    emoji: '🌿',
    role:
      'Potent fat-soluble antioxidant that protects cell membranes from oxidative damage, supports immune function, and helps prevent the oxidation of LDL cholesterol. Alpha-tocopherol is the most biologically active form.',
    deficiency: [
      'Peripheral neuropathy (nerve damage in hands and feet)',
      'Ataxia (impaired coordination and balance)',
      'Muscle weakness',
      'Haemolytic anaemia in newborns',
      'Impaired immune response',
    ],
    sources: [
      'Wheat germ oil',
      'Sunflower and safflower oil',
      'Almonds and sunflower seeds',
      'Hazelnuts',
      'Avocado',
      'Spinach and Swiss chard',
      'Peanuts and peanut butter',
    ],
    rda: '15 mg/day (alpha-tocopherol)',
    upperLimit: '1,000 mg/day (from supplements)',
    tip: 'Get vitamin E from whole food sources like nuts and seeds rather than high-dose supplements, which may interfere with blood clotting at megadoses.',
  },
  {
    id: 'vit_k',
    name: 'Vitamin K',
    category: 'fat_vitamin',
    emoji: '🥦',
    role:
      'Critical for blood coagulation (K1/phylloquinone activates clotting factors) and bone metabolism (K2/menaquinone activates osteocalcin). K2 also helps prevent arterial calcification.',
    deficiency: [
      'Prolonged bleeding and easy bruising',
      'Heavy menstrual periods',
      'Reduced bone density and increased fracture risk',
      'Calcification of soft tissues (low K2)',
      'Haemorrhagic disease in newborns',
    ],
    sources: [
      'Natto (fermented soybeans — highest K2)',
      'Dark leafy greens: kale, spinach, collards (K1)',
      'Broccoli and Brussels sprouts',
      'Parsley and chives',
      'Hard cheeses (Gouda, Edam — K2)',
      'Egg yolks',
      'Chicken and beef liver',
    ],
    rda: '90 mcg/day (women) · 120 mcg/day (men)',
    tip: 'Vitamin K1 in greens is best absorbed with fat. If on warfarin, keep green vegetable intake consistent rather than avoiding them — sudden large changes alter INR.',
  },

  // ─── Water-Soluble Vitamins ─────────────────────────────────────────────
  {
    id: 'vit_b1',
    name: 'Vitamin B1',
    altName: 'Thiamine',
    category: 'water_vitamin',
    emoji: '⚡',
    role:
      'Essential coenzyme in carbohydrate metabolism and ATP production, particularly in the brain and nervous system. Also required for the synthesis of neurotransmitters.',
    deficiency: [
      'Beriberi (wet form: heart failure and oedema; dry form: nerve damage)',
      'Wernicke-Korsakoff syndrome (confusion, eye movement issues, memory loss — seen in alcoholism)',
      'Peripheral neuropathy (tingling, numbness in limbs)',
      'Muscle weakness and fatigue',
      'Impaired cognitive function',
    ],
    sources: [
      'Pork and ham',
      'Whole grains (brown rice, oats, whole wheat)',
      'Legumes (black beans, edamame, lentils)',
      'Sunflower seeds',
      'Nutritional yeast',
      'Fortified breakfast cereals',
      'Trout and tuna',
    ],
    rda: '1.1 mg/day (women) · 1.2 mg/day (men)',
    tip: 'Thiamine is destroyed by heat and leaches into cooking water. Steam or use minimal water when cooking thiamine-rich vegetables, and avoid prolonged boiling.',
  },
  {
    id: 'vit_b2',
    name: 'Vitamin B2',
    altName: 'Riboflavin',
    category: 'water_vitamin',
    emoji: '🟡',
    role:
      'Central component of FAD and FMN coenzymes involved in the electron transport chain and energy metabolism. Also required for activating other B vitamins (B6, folate) and antioxidant recycling (glutathione).',
    deficiency: [
      'Ariboflavinosis: cracked lips and mouth corners (angular cheilitis)',
      'Inflamed, sore tongue (glossitis) that turns magenta',
      'Dry, scaly skin around the nose and mouth',
      'Eye sensitivity to light (photophobia)',
      'Anaemia due to impaired iron absorption',
    ],
    sources: [
      'Beef liver and kidney',
      'Dairy products (milk, yoghurt, cheese)',
      'Eggs',
      'Lean beef and pork',
      'Almonds',
      'Salmon and mackerel',
      'Fortified cereals and grains',
    ],
    rda: '1.1 mg/day (women) · 1.3 mg/day (men)',
    tip: 'Riboflavin is highly light-sensitive — store milk in opaque containers rather than clear glass to preserve its content.',
  },
  {
    id: 'vit_b3',
    name: 'Vitamin B3',
    altName: 'Niacin',
    category: 'water_vitamin',
    emoji: '🔴',
    role:
      'Precursor to NAD⁺ and NADP⁺ coenzymes critical for energy metabolism, DNA repair, and cell signalling. High-dose niacin can also raise HDL cholesterol and lower triglycerides.',
    deficiency: [
      'Pellagra: the "4 Ds" — Dermatitis, Diarrhoea, Dementia, Death (if untreated)',
      'Casal\'s necklace (reddened skin rash on neck)',
      'Inflamed mouth and tongue',
      'Fatigue and irritability',
      'Memory loss and mental confusion',
    ],
    sources: [
      'Chicken breast and turkey',
      'Tuna, salmon, and anchovies',
      'Beef liver',
      'Peanuts and peanut butter',
      'Brown rice',
      'Fortified cereals',
      'Mushrooms (portobello)',
    ],
    rda: '14 mg NE/day (women) · 16 mg NE/day (men)',
    upperLimit: '35 mg/day (from supplements — to avoid flushing)',
    tip: 'The body can convert tryptophan (from protein foods) to niacin at a ratio of 60:1 (mg tryptophan : mg niacin). Adequate protein intake provides a meaningful niacin contribution.',
  },
  {
    id: 'vit_b5',
    name: 'Vitamin B5',
    altName: 'Pantothenic Acid',
    category: 'water_vitamin',
    emoji: '🌾',
    role:
      'Component of Coenzyme A (CoA), which is essential for fatty acid synthesis and oxidation, the Krebs cycle, and synthesis of steroid hormones, neurotransmitters, and haemoglobin.',
    deficiency: [
      'Burning feet syndrome (burning sensation in feet)',
      'Fatigue and general malaise',
      'Headache and irritability',
      'Impaired coordination',
      'Numbness and tingling (rare severe deficiency)',
    ],
    sources: [
      'Beef liver and chicken liver',
      'Sunflower seeds',
      'Salmon and rainbow trout',
      'Avocado',
      'Mushrooms (shiitake, portobello)',
      'Eggs',
      'Lentils and split peas',
    ],
    rda: '5 mg/day (adults, Adequate Intake)',
    tip: 'Pantothenic acid is widely distributed in food — the name comes from Greek "pantos" meaning "everywhere." Genuine deficiency is rare except in severe malnutrition.',
  },
  {
    id: 'vit_b6',
    name: 'Vitamin B6',
    altName: 'Pyridoxine',
    category: 'water_vitamin',
    emoji: '🧠',
    role:
      'Coenzyme (as PLP) in over 100 enzymatic reactions, primarily in amino acid metabolism. Critical for neurotransmitter synthesis (serotonin, dopamine, GABA), haemoglobin production, and immune function.',
    deficiency: [
      'Microcytic anaemia (reduced haemoglobin synthesis)',
      'Peripheral neuropathy (tingling, pain in hands and feet)',
      'Depression, irritability, and confusion',
      'Seborrhoeic dermatitis around the nose and mouth',
      'Weakened immune response',
    ],
    sources: [
      'Chickpeas (garbanzo beans)',
      'Beef liver',
      'Tuna and salmon',
      'Chicken and turkey breast',
      'Potatoes with skin',
      'Bananas',
      'Fortified cereals',
    ],
    rda: '1.3–1.5 mg/day (women) · 1.3–1.7 mg/day (men)',
    upperLimit: '100 mg/day (from supplements)',
    tip: 'B6 is important for PMS symptom management and morning sickness in pregnancy — but doses above 200 mg/day long-term can paradoxically cause nerve damage.',
  },
  {
    id: 'vit_b7',
    name: 'Vitamin B7',
    altName: 'Biotin',
    category: 'water_vitamin',
    emoji: '💅',
    role:
      'Coenzyme for carboxylase enzymes involved in fatty acid synthesis, gluconeogenesis, and amino acid catabolism. Important for gene expression and is often marketed for hair, skin, and nail health.',
    deficiency: [
      'Hair thinning and hair loss',
      'Scaly, red rash around the eyes, nose, and mouth',
      'Brittle nails',
      'Neurological symptoms: depression, lethargy, hallucinations',
      'Impaired immune function',
    ],
    sources: [
      'Beef liver and cooked egg yolks',
      'Salmon',
      'Pork chops',
      'Sunflower seeds',
      'Sweet potato',
      'Almonds',
      'Nutritional yeast',
    ],
    rda: '30 mcg/day (adults, Adequate Intake)',
    tip: 'Raw egg whites contain avidin, a protein that blocks biotin absorption. Cooking egg whites deactivates avidin — another good reason to cook your eggs.',
  },
  {
    id: 'vit_b9',
    name: 'Vitamin B9',
    altName: 'Folate',
    category: 'water_vitamin',
    emoji: '🍃',
    role:
      'Essential for DNA synthesis, repair, and methylation, as well as red blood cell formation and rapid cell division. Critical during pregnancy for neural tube development in the foetus.',
    deficiency: [
      'Megaloblastic anaemia (large, immature red blood cells)',
      'Neural tube defects in newborns (spina bifida, anencephaly)',
      'Fatigue, weakness, and pallor',
      'Mouth sores and swollen tongue',
      'Elevated homocysteine (cardiovascular risk)',
    ],
    sources: [
      'Dark leafy greens (spinach, asparagus, Brussels sprouts)',
      'Black-eyed peas and lentils',
      'Avocado',
      'Beef liver',
      'Edamame',
      'Fortified grains and cereals',
      'Oranges and orange juice',
    ],
    rda: '400 mcg DFE/day · 600 mcg DFE/day during pregnancy',
    upperLimit: '1,000 mcg/day (from folic acid supplements)',
    tip: 'Women who could become pregnant should take 400 mcg of folic acid daily starting at least one month before conception — neural tube closure occurs before many women know they are pregnant.',
  },
  {
    id: 'vit_b12',
    name: 'Vitamin B12',
    altName: 'Cobalamin',
    category: 'water_vitamin',
    emoji: '🔵',
    role:
      'Required for myelin sheath formation (nerve insulation), DNA synthesis, red blood cell production, and one-carbon metabolism alongside folate. Unique in that it is found almost exclusively in animal-derived foods.',
    deficiency: [
      'Pernicious anaemia and megaloblastic anaemia',
      'Peripheral neuropathy and subacute combined degeneration of the spinal cord',
      'Memory loss, cognitive decline, and dementia-like symptoms',
      'Depression, mood changes, and psychosis',
      'Elevated homocysteine and methylmalonic acid',
    ],
    sources: [
      'Clams and oysters (extremely high)',
      'Beef liver and kidney',
      'Salmon, tuna, and sardines',
      'Beef and lamb',
      'Dairy (milk, yoghurt, cheese)',
      'Eggs',
      'Fortified nutritional yeast and plant milks',
    ],
    rda: '2.4 mcg/day (adults)',
    tip: 'Vegans and older adults (who absorb B12 less efficiently) should supplement or eat fortified foods regularly. Methylcobalamin or hydroxocobalamin forms may be better absorbed than cyanocobalamin for some people.',
  },
  {
    id: 'vit_c',
    name: 'Vitamin C',
    altName: 'Ascorbic Acid',
    category: 'water_vitamin',
    emoji: '🍊',
    role:
      'Powerful water-soluble antioxidant essential for collagen synthesis (wound healing, skin, joint integrity), enhancing non-haem iron absorption, neurotransmitter synthesis, and immune function.',
    deficiency: [
      'Scurvy: bleeding gums, loose teeth, and easy bruising',
      'Fatigue, weakness, and depression',
      'Poor wound healing and reopening of old wounds',
      'Swollen, painful joints (haemarthrosis)',
      'Corkscrew-shaped body hair (perifollicular haemorrhage)',
    ],
    sources: [
      'Kakadu plum and acerola cherries (extremely high)',
      'Red and yellow bell peppers',
      'Kiwi fruit',
      'Oranges, grapefruits, and strawberries',
      'Broccoli and Brussels sprouts',
      'Guava',
      'Tomatoes and tomato juice',
    ],
    rda: '75 mg/day (women) · 90 mg/day (men) · +35 mg/day for smokers',
    upperLimit: '2,000 mg/day',
    tip: 'Take vitamin C with plant-based iron sources (beans, lentils, fortified cereals) to dramatically increase non-haem iron absorption — particularly useful for vegetarians.',
  },

  // ─── Macrominerals ──────────────────────────────────────────────────────
  {
    id: 'calcium',
    name: 'Calcium',
    category: 'macromineral',
    emoji: '🦴',
    role:
      'The most abundant mineral in the body, constituting about 99% of bones and teeth. Also essential for muscle contraction, nerve signal transmission, blood clotting, and enzyme activation.',
    deficiency: [
      'Hypocalcaemia: muscle cramps, spasms, and tetany',
      'Osteopenia and osteoporosis (long-term)',
      'Rickets (in children)',
      'Numbness and tingling in hands and feet',
      'Irregular heartbeat in severe cases',
    ],
    sources: [
      'Dairy: milk, yoghurt, hard cheese',
      'Calcium-set tofu',
      'Sardines and canned salmon (with bones)',
      'Fortified plant milks (soy, almond, oat)',
      'Dark leafy greens: kale, bok choy, broccoli',
      'Almonds',
      'White beans and edamame',
    ],
    rda: '1,000 mg/day (adults) · 1,200 mg/day (women 51+ and men 71+)',
    upperLimit: '2,500 mg/day',
    tip: 'The body absorbs calcium best in doses of 500 mg or less. Split supplements through the day and take with food to maximise absorption and reduce kidney stone risk.',
  },
  {
    id: 'magnesium',
    name: 'Magnesium',
    category: 'macromineral',
    emoji: '💪',
    role:
      'Cofactor for over 300 enzymes involved in ATP synthesis, protein synthesis, DNA repair, blood glucose regulation, and muscle and nerve function. About 60% is stored in bone.',
    deficiency: [
      'Muscle cramps and spasms (especially nocturnal leg cramps)',
      'Fatigue and weakness',
      'Anxiety, irritability, and sleep disturbances',
      'Cardiac arrhythmias',
      'Low calcium and potassium (magnesium regulates their transport)',
    ],
    sources: [
      'Pumpkin seeds (highest per serving)',
      'Dark chocolate (70%+ cocoa)',
      'Black beans and edamame',
      'Almonds, cashews, and Brazil nuts',
      'Spinach and Swiss chard',
      'Whole grains (quinoa, brown rice, oats)',
      'Avocado',
    ],
    rda: '310–320 mg/day (women) · 400–420 mg/day (men)',
    upperLimit: '350 mg/day (from supplements only)',
    tip: 'Magnesium glycinate or malate causes less GI discomfort than magnesium oxide (the cheap form). Taking 200–400 mg before bed may improve sleep quality and reduce leg cramps.',
  },
  {
    id: 'potassium',
    name: 'Potassium',
    category: 'macromineral',
    emoji: '🍌',
    role:
      'The primary intracellular cation, essential for maintaining fluid balance, cell membrane potential, nerve signal transmission, muscle contraction, and counteracting the blood pressure–raising effects of sodium.',
    deficiency: [
      'Hypokalaemia: muscle weakness, cramps, and paralysis',
      'Cardiac arrhythmias and palpitations',
      'Constipation and bloating',
      'Fatigue and general weakness',
      'Increased blood pressure (with low potassium intake)',
    ],
    sources: [
      'Beet greens and Swiss chard',
      'Potatoes and sweet potatoes (with skin)',
      'Avocado',
      'Beans and lentils',
      'Bananas',
      'Dried fruits: apricots, prunes, raisins',
      'Salmon and halibut',
    ],
    rda: '2,600 mg/day (women) · 3,400 mg/day (men) — Adequate Intake',
    tip: 'A high-potassium diet can meaningfully lower blood pressure, especially when combined with reduced sodium. Aim for a potassium-to-sodium ratio greater than 1:1 in your diet.',
  },
  {
    id: 'sodium',
    name: 'Sodium',
    category: 'macromineral',
    emoji: '🧂',
    role:
      'Principal extracellular cation that regulates fluid balance, blood volume, and blood pressure. Essential for nerve impulse transmission and muscle contraction via the sodium-potassium ATPase pump.',
    deficiency: [
      'Hyponatraemia: nausea, headache, and confusion',
      'Muscle weakness and cramps',
      'Lethargy and fatigue',
      'Seizures (severe deficiency)',
      'Coma (extreme cases)',
    ],
    sources: [
      'Table salt and sea salt',
      'Processed and packaged foods',
      'Canned soups and vegetables',
      'Bread and baked goods',
      'Cheese',
      'Cured meats (bacon, ham)',
      'Soy sauce and condiments',
    ],
    rda: '1,500 mg/day (Adequate Intake) · <2,300 mg/day (upper limit)',
    upperLimit: '2,300 mg/day',
    tip: 'Over 70% of dietary sodium comes from processed foods, not the salt shaker. Reading nutrition labels and cooking from scratch are the most effective strategies for sodium reduction.',
  },
  {
    id: 'phosphorus',
    name: 'Phosphorus',
    category: 'macromineral',
    emoji: '🔋',
    role:
      'Second most abundant mineral in the body after calcium; key component of hydroxyapatite in bones and teeth, ATP (cellular energy currency), DNA/RNA backbone, and cell membrane phospholipids.',
    deficiency: [
      'Hypophosphataemia: muscle weakness and bone pain',
      'Impaired bone mineralisation',
      'Fatigue and reduced exercise capacity',
      'Nervous system dysfunction (rare severe cases)',
      'Anaemia (impaired red blood cell function)',
    ],
    sources: [
      'Dairy products (milk, yoghurt, cheese)',
      'Salmon and halibut',
      'Lean meats and poultry',
      'Eggs',
      'Legumes (lentils, kidney beans)',
      'Pumpkin seeds and sunflower seeds',
      'Whole grains',
    ],
    rda: '700 mg/day (adults)',
    upperLimit: '4,000 mg/day',
    tip: 'Phosphorus deficiency is extremely rare in developed countries — almost all protein foods are rich in it. Those with kidney disease, however, may need to limit high-phosphorus foods.',
  },

  // ─── Trace Minerals ─────────────────────────────────────────────────────
  {
    id: 'iron',
    name: 'Iron',
    category: 'trace_mineral',
    emoji: '🩸',
    role:
      'Central component of haemoglobin (carries oxygen in red blood cells) and myoglobin (stores oxygen in muscle). Also essential for mitochondrial ATP production and numerous enzymatic reactions.',
    deficiency: [
      'Iron-deficiency anaemia: fatigue, pallor, and shortness of breath',
      'Brittle nails and spoon-shaped nails (koilonychia)',
      'Restless leg syndrome',
      'Pica (craving non-food items like ice or dirt)',
      'Impaired cognitive function and reduced work capacity',
    ],
    sources: [
      'Beef liver and organ meats (haem iron)',
      'Clams and oysters',
      'Red meat (beef, lamb)',
      'Dark turkey meat',
      'Tofu and tempeh (non-haem)',
      'Lentils and kidney beans (non-haem)',
      'Fortified cereals and dark leafy greens',
    ],
    rda: '18 mg/day (pre-menopausal women) · 8 mg/day (men and post-menopausal women)',
    upperLimit: '45 mg/day',
    tip: 'Haem iron from meat is absorbed at 15–35%; non-haem iron from plants at 2–20%. Eat non-haem iron sources alongside vitamin C and avoid tea or coffee within an hour of iron-rich meals.',
  },
  {
    id: 'zinc',
    name: 'Zinc',
    category: 'trace_mineral',
    emoji: '🛡️',
    role:
      'Essential for over 300 enzyme reactions, immune cell function and signalling, DNA synthesis, protein synthesis, wound healing, taste and smell perception, and testosterone production.',
    deficiency: [
      'Impaired immune function and frequent infections',
      'Delayed wound healing',
      'Loss of taste and smell (hypogeusia/anosmia)',
      'Dermatitis, especially around mouth, hands, and feet',
      'Stunted growth and sexual development in children',
    ],
    sources: [
      'Oysters (highest food source by far)',
      'Beef and lamb',
      'Pumpkin seeds',
      'Hemp seeds',
      'Wheat germ',
      'Chickpeas and lentils (lower bioavailability)',
      'Dark chocolate',
    ],
    rda: '8 mg/day (women) · 11 mg/day (men)',
    upperLimit: '40 mg/day',
    tip: 'Phytates in legumes and whole grains bind zinc and reduce absorption. Soaking, sprouting, or fermenting grains and beans reduces phytate content and improves zinc bioavailability for plant-based eaters.',
  },
  {
    id: 'selenium',
    name: 'Selenium',
    category: 'trace_mineral',
    emoji: '🌰',
    role:
      'Incorporated into selenoproteins that act as antioxidant enzymes (glutathione peroxidase), regulate thyroid hormone metabolism (converting T4 to active T3), and support immune and reproductive function.',
    deficiency: [
      'Keshan disease (endemic cardiomyopathy in selenium-poor regions)',
      'Kashin-Beck disease (joint and bone disease)',
      'Impaired thyroid function and hypothyroidism',
      'Male infertility (reduced sperm motility)',
      'Weakened antioxidant defence',
    ],
    sources: [
      'Brazil nuts (1–2 nuts meets daily needs)',
      'Tuna and sardines',
      'Halibut and shrimp',
      'Beef and chicken',
      'Eggs',
      'Sunflower seeds',
      'Whole wheat bread (soil-dependent)',
    ],
    rda: '55 mcg/day (adults)',
    upperLimit: '400 mcg/day',
    tip: 'Just 1–2 Brazil nuts per day provides your full selenium RDA — but avoid eating a handful daily as selenium toxicity (selenosis) causes hair loss, nail brittleness, and neurological issues.',
  },
  {
    id: 'iodine',
    name: 'Iodine',
    category: 'trace_mineral',
    emoji: '🦋',
    role:
      'Exclusively used for synthesising thyroid hormones (T3 and T4) that regulate metabolism, growth, brain development, and body temperature. Critical during pregnancy for foetal brain development.',
    deficiency: [
      'Goitre (enlarged thyroid gland)',
      'Hypothyroidism: fatigue, weight gain, cold intolerance, constipation',
      'Cretinism (severe intellectual disability in children born to deficient mothers)',
      'Impaired brain development and IQ reduction',
      'Pregnancy complications and miscarriage',
    ],
    sources: [
      'Seaweed (nori, wakame, kelp — variable)',
      'Iodised table salt',
      'Cod and tuna',
      'Shrimp and other seafood',
      'Dairy milk and yoghurt',
      'Eggs',
      'Potatoes with skin',
    ],
    rda: '150 mcg/day (adults) · 220 mcg/day (pregnancy) · 290 mcg/day (lactation)',
    upperLimit: '1,100 mcg/day',
    tip: 'Sea salt and gourmet salts are NOT reliably iodised — check the label. Using iodised table salt in cooking or eating seafood 2–3× per week is the simplest way to meet iodine needs.',
  },
  {
    id: 'copper',
    name: 'Copper',
    category: 'trace_mineral',
    emoji: '🟤',
    role:
      'Component of enzymes involved in iron metabolism (ceruloplasmin), collagen and elastin synthesis, neurotransmitter production, antioxidant defence (superoxide dismutase), and energy production.',
    deficiency: [
      'Anaemia unresponsive to iron supplementation',
      'Neutropenia (low white blood cells)',
      'Bone abnormalities and fractures',
      'Neurological problems: weakness, poor coordination',
      'Pale skin and loss of pigmentation',
    ],
    sources: [
      'Beef liver (extremely high)',
      'Oysters and shellfish',
      'Dark chocolate and cocoa powder',
      'Spirulina',
      'Cashews and almonds',
      'Sesame seeds and tahini',
      'Shiitake mushrooms',
    ],
    rda: '900 mcg/day (adults)',
    upperLimit: '10,000 mcg/day',
    tip: 'High-dose zinc supplementation (50+ mg/day) significantly impairs copper absorption and can cause copper deficiency — always balance zinc with copper intake if supplementing long-term.',
  },
  {
    id: 'manganese',
    name: 'Manganese',
    category: 'trace_mineral',
    emoji: '🌿',
    role:
      'Cofactor for enzymes involved in bone formation, carbohydrate and cholesterol metabolism, antioxidant defence (mitochondrial superoxide dismutase), and wound healing via collagen synthesis.',
    deficiency: [
      'Impaired bone formation and skeletal abnormalities',
      'Impaired glucose tolerance and carbohydrate metabolism',
      'Skin rash (dermatitis)',
      'Reduced fertility',
      'Altered lipid metabolism',
    ],
    sources: [
      'Mussels and clams',
      'Hazelnuts and pecans',
      'Brown rice and oats',
      'Chickpeas and black-eyed peas',
      'Spinach',
      'Pineapple',
      'Tea (high in manganese)',
    ],
    rda: '1.8 mg/day (women) · 2.3 mg/day (men) — Adequate Intake',
    upperLimit: '11 mg/day',
    tip: 'Manganese deficiency is rare. However, excessive manganese from contaminated water or industrial exposure is more concerning and can cause a Parkinson\'s-like neurological condition (manganism).',
  },
  {
    id: 'chromium',
    name: 'Chromium',
    category: 'trace_mineral',
    emoji: '💎',
    role:
      'Enhances insulin sensitivity by potentiating insulin signalling at the cellular level, supporting glucose metabolism and carbohydrate utilisation. May also play a role in macronutrient metabolism.',
    deficiency: [
      'Impaired glucose tolerance and insulin resistance',
      'Elevated blood sugar and increased diabetes risk',
      'Elevated cholesterol and triglycerides',
      'Peripheral neuropathy (rare)',
      'Weight gain and metabolic dysfunction',
    ],
    sources: [
      'Broccoli (best food source)',
      'Grape juice and orange juice',
      'Whole wheat products',
      'Beef',
      'Garlic',
      'Basil and dried herbs',
      'Green beans',
    ],
    rda: '25 mcg/day (women) · 35 mcg/day (men) — Adequate Intake',
    tip: 'Chromium picolinate is the most studied supplemental form. Evidence for blood sugar benefits is modest — prioritise balanced meals, fibre, and exercise for insulin sensitivity over supplementation.',
  },
];
